CREATE TABLE C50SW00.TSW00ENCA 
(
  ENCARGO_ID VARCHAR2(15 BYTE) NOT NULL 
, CREATED_DT TIMESTAMP(6) NOT NULL 
, CREATED_BY_ID VARCHAR2(15 BYTE) NOT NULL 
, LAST_UPD_DT TIMESTAMP(6) NOT NULL 
, LAST_UPD_BY_ID VARCHAR2(15 BYTE) NOT NULL 
, MODIFICATION_NUM NUMBER(10, 0) NOT NULL 
, SINIESTRO_ID VARCHAR2(15 BYTE) NOT NULL 
, JOB_TYPE_CD VARCHAR2(50 BYTE) NOT NULL 
, ENCA_JOB_SUBTYPE_CD VARCHAR2(50 BYTE) 
, ID_ENCARGO_RD NUMBER 
, ID_ENCARGO_CIA VARCHAR2(20 BYTE) 
, ENCA_STATUS_CD VARCHAR2(50 BYTE) 
, ENCA_STATUS_DT DATE 
, EXPECTED_DT DATE 
, REQUESTED_BY_ID VARCHAR2(15 BYTE) 
, ENCA_REQUESTED_BY_CD VARCHAR2(50 BYTE) 
, ENCA_ASGN_TYPE_CD VARCHAR2(50 BYTE) 
, ENCA_ASGN_REASON_TYPE_CD VARCHAR2(50 BYTE) 
, ENCA_ASGN_CHANNEL_CD VARCHAR2(50 BYTE) 
, ENCA_ASGN_DT DATE 
, PROFESSIONAL_TYPE_CD VARCHAR2(50 BYTE) 
, ID_PROVEEDOR_CIA VARCHAR2(15 BYTE) 
, PROFESSIONAL_SKILL_CD VARCHAR2(50 BYTE) 
, OPEN_DT DATE 
, CLOSED_DT DATE 
, DELIVERY_DT DATE 
, CONTACTO_ID VARCHAR2(15 BYTE) 
, AFECTADO_ID VARCHAR2(15 BYTE) 
, PRESTACION_ID VARCHAR2(15 BYTE) 
, FRANJA_M_FLG CHAR(1 BYTE) DEFAULT '0' 
, FRANJA_T_FLG CHAR(1 BYTE) DEFAULT '0' 
, URGENTE_FLG CHAR(1 BYTE) DEFAULT '0' 
, OBLIGATION_FLG CHAR(1 BYTE) DEFAULT '0' 
, ENCA_LUGAR_INTERVENCION_CD VARCHAR2(50 BYTE) 
, COMENTARIOS VARCHAR2(250 BYTE) 
, DESCRIPCION VARCHAR2(255 BYTE) DEFAULT NULL 
, ENCA_REASON_TYPE_CD VARCHAR2(50 BYTE) 
, ENCA_SERVICIOS_ADICIONALES_CD VARCHAR2(50 BYTE) 
, ENCA_ESPECIALIDADES_CD VARCHAR2(50 BYTE) 
, ENCA_CATEGORY_CD VARCHAR2(50 BYTE) 
, ENCA_AUTORIDAD_CD VARCHAR2(50 BYTE) 
, NUM_ATESTADO VARCHAR2(50 BYTE) 
, ENVIAR_ORIGINAL_FLG CHAR(1 BYTE) DEFAULT '0' 
, LOC_DESC VARCHAR2(50 BYTE) 
, LOC_TYPE_CD VARCHAR2(2 BYTE) 
, LOC_ADDR VARCHAR2(50 BYTE) 
, LOC_CITY VARCHAR2(50 BYTE) 
, LOC_COUNTY_CD VARCHAR2(50 BYTE) 
, LOC_ZIP VARCHAR2(5 BYTE) 
, PRINCIPAL_FLG CHAR(1 BYTE) 
, ENCA_REPORTED_BY_CD VARCHAR2(50 BYTE) 
, MOTIVO_URGENTE_CD VARCHAR2(50 BYTE) 
, ENCA_ASIGNADO VARCHAR2(15 BYTE) 
, ENCA_TIPO_ASIGNADO_CD VARCHAR2(15 BYTE) 
, ORDEN_PROFESIONAL NUMBER(10, 0) 
, PROF_CONSULTADOS VARCHAR2(250 BYTE) 
, SRRA_DRS_FLG CHAR(1 BYTE) 
, OBSERVACIONES_TALLER VARCHAR2(250 BYTE) 
, SERVICIO_OFICIAL_FLG CHAR(1 BYTE) 
, PERITO_AUTOM_CD VARCHAR2(15 BYTE) 
, REQ_PER_PRE_FLG CHAR(1 BYTE) 
, DAMAGE_ESTIMATE NUMBER(22, 7) 
, CONSTRAINT ISW00ENCA_PK PRIMARY KEY 
  (
    ENCARGO_ID 
  )
